spring:
  application:
    name: projetoColegioColibri
  profiles:
    active: local
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/bd_projeto_colegio_colibri
    driverClassName: com.mysql.cj.jdbc.Driver



