spring:
  docker:
    compose:
      enabled: true
      file: docker/docker-compose.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/bd_projeto_colegio_colibri
    username: root
    password: root

