spring:
  application:
    name: projetoColegioColibri
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/bd_projeto_colegio_colibri
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
